package com.rl.taskup.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005AB4)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0072E2)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF415F91)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA7C4FD)
val onSecondaryContainerLight = Color(0xFF325182)
val tertiaryLight = Color(0xFF8B30AE)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA64CCA)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C23)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF181C23)
val surfaceVariantLight = Color(0xFFDDE2F3)
val onSurfaceVariantLight = Color(0xFF414754)
val outlineLight = Color(0xFF717786)
val outlineVariantLight = Color(0xFFC1C6D6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3038)
val inverseOnSurfaceLight = Color(0xFFEEF0FB)
val inversePrimaryLight = Color(0xFFAAC7FF)
val surfaceDimLight = Color(0xFFD7DAE4)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F3FE)
val surfaceContainerLight = Color(0xFFEBEDF8)
val surfaceContainerHighLight = Color(0xFFE6E8F2)
val surfaceContainerHighestLight = Color(0xFFE0E2ED)




val primaryDark = Color(0xFFAAC7FF)
val onPrimaryDark = Color(0xFF002F64)
val primaryContainerDark = Color(0xFF4090FF)
val onPrimaryContainerDark = Color(0xFF001E44)
val secondaryDark = Color(0xFFAAC7FF)
val onSecondaryDark = Color(0xFF0A305F)
val secondaryContainerDark = Color(0xFF2A497A)
val onSecondaryContainerDark = Color(0xFF9BB9F1)
val tertiaryDark = Color(0xFFEDB1FF)
val onTertiaryDark = Color(0xFF530070)
val tertiaryContainerDark = Color(0xFFC66AE9)
val onTertiaryContainerDark = Color(0xFF37004C)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131B)
val onBackgroundDark = Color(0xFFE0E2ED)
val surfaceDark = Color(0xFF10131B)
val onSurfaceDark = Color(0xFFE0E2ED)
val surfaceVariantDark = Color(0xFF414754)
val onSurfaceVariantDark = Color(0xFFC1C6D6)
val outlineDark = Color(0xFF8B91A0)
val outlineVariantDark = Color(0xFF414754)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2ED)
val inverseOnSurfaceDark = Color(0xFF2D3038)
val inversePrimaryDark = Color(0xFF005DB9)
val surfaceDimDark = Color(0xFF10131B)
val surfaceBrightDark = Color(0xFF363941)
val surfaceContainerLowestDark = Color(0xFF0B0E15)
val surfaceContainerLowDark = Color(0xFF181C23)
val surfaceContainerDark = Color(0xFF1C2027)
val surfaceContainerHighDark = Color(0xFF262A32)
val surfaceContainerHighestDark = Color(0xFF31353D)
